* ============================================================
* Script: 08_outlier_flags.do
* Purpose: Systematic data-quality flags for firm-level fuel and
*          electricity consumption in si_energy_harmonized.dta.
*
*          Five-dimension flagging strategy (FLAG, NEVER DELETE):
*
*            D1 — Cross-sectional IQR outlier
*                 |log(v) - cell_median| > k × cell_IQR
*                 k = 3.0 moderate; k = 5.0 severe
*                 Cell = ISIC2 × year (fallback to year if N < 10)
*
*            D2 — Longitudinal growth-rate outlier
*                 |Δlog(v)| > threshold for consecutive firm-years
*                 Moderate: |Δlog| > log(10) [10× change]
*                 Severe:   |Δlog| > log(50) [50× change]
*
*            D3 — Fuel intensity outlier (fuel per worker)
*                 Same IQR logic as D1 applied to log(fuel / ltlnou)
*                 Catches absolute-level errors invisible in cross-section
*                 NOTE: uses workers, NOT output → no circularity with
*                 energy-efficiency outcome variable
*
*          Composite outputs:
*            flag_n_dims     — count of dimensions triggered (0–3+)
*            flag_any_mod    — any moderate flag
*            flag_any_sev    — any severe flag
*
*          Design principles:
*            - Never drops observations (flags only)
*            - Thresholds conservative to minimise false positives
*            - Structural gap years correctly excluded from D1/D2
*
*          Robustness table recommendations:
*            Baseline:   full sample
*            Conservative: drop if n_flags >= 2
*            Stringent:  drop if flag_any_sev == 1
*            (flag_any_hard removed — not generated by current pipeline)
*
* Input:   output/si_energy_harmonized.dta
* Output:  output/si_energy_flagged.dta
*          output/tables/flag_summary_by_year.csv
*          output/tables/flag_summary_by_isic2.csv
*
* Author:  Albert Ludi
* Date:    2026-03-20
* ============================================================

clear all
set more off
capture log close

* ── Paths (all derived from $handoff — set via dofiles/00_config.do) ──────────────
if "$handoff" == "" {
    di as error "ERROR: global 'handoff' is not set."
    di as error "       Run: do {path_to_handoff}/dofiles/00_config.do"
    exit 1
}
global root    "$handoff"
global sidata  "$handoff/data/si_annual"
global output  "$handoff/output"
global logs    "$handoff/logs"
global rawdata "$handoff/data/raw"
global concord "$handoff/data/concordance"
global dofiles "$handoff/dofiles"
global tables  "$handoff/output/tables"

capture mkdir "$tables"
log using "$logs/08_outlier_flags.log", replace text

use "$output/si_energy_harmonized.dta", clear
di as txt "Obs loaded: " _N

* ── Derive isic2 if not present ─────────────────────────────────────────────
cap confirm variable isic2
if _rc != 0 {
    cap gen isic2 = int(isic5_raw / 1000) if !missing(isic5_raw)
    cap gen isic3 = int(isic5_raw / 100)  if !missing(isic5_raw)
    di as txt "  isic2 derived from isic5_raw"
}

* ── Quality gate ────────────────────────────────────────────────────────────
di as txt _n "=== Quality gate ==="
count if missing(psid)
if r(N) > 0 di as error "WARNING: " r(N) " obs with missing psid"
duplicates report psid year
count if missing(isic2)
di as txt "  Missing isic2: " r(N) " obs"
count if missing(ltlnou) | ltlnou == 0
di as txt "  Missing/zero ltlnou: " r(N) " obs"

* ── Set panel ────────────────────────────────────────────────────────────────
xtset psid year

* ── Variables to flag (D1, D2, D3) ─────────────────────────────────────────
* All variables used in the emission conversion pipeline (Scope 1 + Scope 2).
* Sparse variables (coalbriq, othergas, coke) are included deliberately so that
* every input to co2_scope1_s1 is subject to the same QC treatment.
* Gap years are hardcoded per variable to suppress D2 flags across structural gaps.
local flag_vars "fuel_diesel_ltr fuel_petrol_ltr fuel_kerosene_ltr fuel_coal_kg fuel_lpg_kg fuel_citygas_m3 fuel_coalbriq_kg fuel_othergas_m3 fuel_coke_kg elec_pln_kwh elec_nonpln_kwh"

* Gap years per variable: in these years the variable was not collected.
* D2 flags suppressed when the lag crosses a gap year.
local gap_fuel_kerosene_ltr  "2001 2002"
local gap_fuel_coal_kg        "2001 2002"
local gap_fuel_lpg_kg         "2001 2002 2003 2004 2005"
local gap_fuel_citygas_m3     "2001 2002 2003 2004 2005"
local gap_fuel_coalbriq_kg    "2011"            // available 2012–2014 only
local gap_fuel_othergas_m3    "2011"            // available 2012–2014 only
local gap_fuel_coke_kg        "2001 2002 2003 2004 2005"  // available 2000 and 2006 only
local gap_fuel_diesel_ltr     ""
local gap_fuel_petrol_ltr     ""
local gap_elec_pln_kwh        ""
local gap_elec_nonpln_kwh     ""

* ── Thresholds (document here for reproducibility) ──────────────────────────
local k_mod = 3.0          // D1/D3: moderate IQR multiplier
local k_sev = 5.0          // D1/D3: severe IQR multiplier
local ln_mod = log(10)     // D2: moderate log-ratio threshold (~2.303)
local ln_sev = log(50)     // D2: severe log-ratio threshold (~3.912)
local n_full = 30          // min N for both tiers (D1/D3)
local n_sev_only = 10      // min N for severe-only tier (D1/D3)

di as txt _n "Thresholds:"
di as txt "  D1/D3 moderate: k = `k_mod' × IQR (cell N ≥ `n_full')"
di as txt "  D1/D3 severe:   k = `k_sev' × IQR (cell N ≥ `n_sev_only')"
di as txt "  D2 moderate: |Δlog| > log(10) = " %6.4f `ln_mod'
di as txt "  D2 severe:   |Δlog| > log(50) = " %6.4f `ln_sev'

* ============================================================
* SECTION 1 — D1: CROSS-SECTIONAL IQR OUTLIER
* ============================================================
* Uses collapse/merge for speed (avoids slow bysort:egen pctile loops).
* Two tiers per variable; fallback from ISIC2×year to year-level for
* cells below minimum N.

di as txt _n "=== D1: Cross-sectional IQR outlier ==="

foreach v of local flag_vars {

    gen byte flag_D1_`v'_mod = .
    gen byte flag_D1_`v'_sev = .

    * Log-transform positive observations
    gen double _logv = log(`v') if `v' > 0 & !missing(`v')

    * ── ISIC2 × year cell percentiles ──────────────────────────────────────
    preserve
        keep if !missing(_logv) & !missing(isic2)
        bysort isic2 year: gen int _npos = _N
        collapse (p25) q1 = _logv ///
                 (p75) q3 = _logv ///
                 (p50) p50 = _logv ///
                 (count) n_cell = _logv, by(isic2 year)
        gen double iqr   = q3 - q1
        gen double lo3   = q1 - `k_mod' * iqr
        gen double hi3   = q3 + `k_mod' * iqr
        gen double lo5   = q1 - `k_sev' * iqr
        gen double hi5   = q3 + `k_sev' * iqr
        keep isic2 year lo3 hi3 lo5 hi5 n_cell
        tempfile d1_cell_`v'
        save `d1_cell_`v''
    restore

    merge m:1 isic2 year using `d1_cell_`v'', ///
        keepusing(lo3 hi3 lo5 hi5 n_cell) nogen keep(master match)

    * ── Year-level fallback percentiles (for small cells) ─────────────────
    preserve
        keep if !missing(_logv)
        collapse (p25) q1y = _logv ///
                 (p75) q3y = _logv, by(year)
        gen double iqry  = q3y - q1y
        gen double lo3y  = q1y - `k_mod' * iqry
        gen double hi3y  = q3y + `k_mod' * iqry
        gen double lo5y  = q1y - `k_sev' * iqry
        gen double hi5y  = q3y + `k_sev' * iqry
        keep year lo3y hi3y lo5y hi5y
        tempfile d1_year_`v'
        save `d1_year_`v''
    restore

    merge m:1 year using `d1_year_`v'', ///
        keepusing(lo3y hi3y lo5y hi5y) nogen keep(master match)

    * ── Apply flags ─────────────────────────────────────────────────────────
    * Large cells (N ≥ 30): both tiers from cell-level thresholds
    replace flag_D1_`v'_mod = ((_logv < lo3 | _logv > hi3) & !missing(_logv)) ///
        if n_cell >= `n_full' & !missing(n_cell)
    replace flag_D1_`v'_sev = ((_logv < lo5 | _logv > hi5) & !missing(_logv)) ///
        if n_cell >= `n_full' & !missing(n_cell)

    * Medium cells (N 10–29): severe only from cell-level thresholds
    replace flag_D1_`v'_mod = 0 ///
        if n_cell >= `n_sev_only' & n_cell < `n_full' & !missing(n_cell)
    replace flag_D1_`v'_sev = ((_logv < lo5 | _logv > hi5) & !missing(_logv)) ///
        if n_cell >= `n_sev_only' & n_cell < `n_full' & !missing(n_cell)

    * Small cells (N < 10): year-level fallback for both tiers
    replace flag_D1_`v'_mod = ((_logv < lo3y | _logv > hi3y) & !missing(_logv)) ///
        if (n_cell < `n_sev_only' | missing(n_cell)) & !missing(_logv)
    replace flag_D1_`v'_sev = ((_logv < lo5y | _logv > hi5y) & !missing(_logv)) ///
        if (n_cell < `n_sev_only' | missing(n_cell)) & !missing(_logv)

    * Missing value if the observation itself is missing/zero (no flag meaningful)
    replace flag_D1_`v'_mod = . if missing(`v') | `v' == 0
    replace flag_D1_`v'_sev = . if missing(`v') | `v' == 0

    label variable flag_D1_`v'_mod "D1 mod: cross-sect IQR outlier k=`k_mod' (`v')"
    label variable flag_D1_`v'_sev "D1 sev: cross-sect IQR outlier k=`k_sev' (`v')"

    drop _logv lo3 hi3 lo5 hi5 n_cell lo3y hi3y lo5y hi5y

    quietly count if flag_D1_`v'_mod == 1
    local n_mod = r(N)
    quietly count if flag_D1_`v'_sev == 1
    di as txt "  `v': mod=" `n_mod' "  sev=" r(N)
}

* ============================================================
* SECTION 3 — D3: FUEL INTENSITY OUTLIER (fuel per worker)
* ============================================================
di as txt _n "=== D3: Fuel intensity outlier (per worker) ==="

cap confirm variable ltlnou
if _rc != 0 {
    di as error "  ltlnou not found — D3 skipped. Re-run 01_append_si_energy.do."
}
else {

    foreach v of local flag_vars {

        gen byte flag_D3_`v'_mod = .
        gen byte flag_D3_`v'_sev = .

        * Intensity: fuel per worker (only where both positive)
        gen double _intv = `v' / ltlnou ///
            if `v' > 0 & !missing(`v') & ltlnou > 0 & !missing(ltlnou)
        gen double _log_intv = log(_intv) if !missing(_intv)

        * ISIC2 × year cell percentiles for intensity
        preserve
            keep if !missing(_log_intv) & !missing(isic2)
            collapse (p25) q1i = _log_intv ///
                     (p75) q3i = _log_intv ///
                     (count) n_ci = _log_intv, by(isic2 year)
            gen double iqri  = q3i - q1i
            gen double lo3i  = q1i - `k_mod' * iqri
            gen double hi3i  = q3i + `k_mod' * iqri
            gen double lo5i  = q1i - `k_sev' * iqri
            gen double hi5i  = q3i + `k_sev' * iqri
            keep isic2 year lo3i hi3i lo5i hi5i n_ci
            tempfile d3_cell_`v'
            save `d3_cell_`v''
        restore

        merge m:1 isic2 year using `d3_cell_`v'', ///
            keepusing(lo3i hi3i lo5i hi5i n_ci) nogen keep(master match)

        * Year-level fallback
        preserve
            keep if !missing(_log_intv)
            collapse (p25) q1iy = _log_intv ///
                     (p75) q3iy = _log_intv, by(year)
            gen double iqriy = q3iy - q1iy
            gen double lo3iy = q1iy - `k_mod' * iqriy
            gen double hi3iy = q3iy + `k_mod' * iqriy
            gen double lo5iy = q1iy - `k_sev' * iqriy
            gen double hi5iy = q3iy + `k_sev' * iqriy
            keep year lo3iy hi3iy lo5iy hi5iy
            tempfile d3_year_`v'
            save `d3_year_`v''
        restore

        merge m:1 year using `d3_year_`v'', ///
            keepusing(lo3iy hi3iy lo5iy hi5iy) nogen keep(master match)

        * Apply flags — same N-based tiering as D1
        replace flag_D3_`v'_mod = ((_log_intv < lo3i | _log_intv > hi3i) & !missing(_log_intv)) ///
            if n_ci >= `n_full' & !missing(n_ci)
        replace flag_D3_`v'_sev = ((_log_intv < lo5i | _log_intv > hi5i) & !missing(_log_intv)) ///
            if n_ci >= `n_full' & !missing(n_ci)

        replace flag_D3_`v'_mod = 0 ///
            if n_ci >= `n_sev_only' & n_ci < `n_full' & !missing(n_ci)
        replace flag_D3_`v'_sev = ((_log_intv < lo5i | _log_intv > hi5i) & !missing(_log_intv)) ///
            if n_ci >= `n_sev_only' & n_ci < `n_full' & !missing(n_ci)

        replace flag_D3_`v'_mod = ((_log_intv < lo3iy | _log_intv > hi3iy) & !missing(_log_intv)) ///
            if (n_ci < `n_sev_only' | missing(n_ci)) & !missing(_log_intv)
        replace flag_D3_`v'_sev = ((_log_intv < lo5iy | _log_intv > hi5iy) & !missing(_log_intv)) ///
            if (n_ci < `n_sev_only' | missing(n_ci)) & !missing(_log_intv)

        replace flag_D3_`v'_mod = . if missing(`v') | `v' == 0
        replace flag_D3_`v'_sev = . if missing(`v') | `v' == 0

        label variable flag_D3_`v'_mod "D3 mod: intensity (fuel/worker) IQR outlier k=`k_mod' (`v')"
        label variable flag_D3_`v'_sev "D3 sev: intensity (fuel/worker) IQR outlier k=`k_sev' (`v')"

        drop _intv _log_intv lo3i hi3i lo5i hi5i n_ci lo3iy hi3iy lo5iy hi5iy

        quietly count if flag_D3_`v'_mod == 1
        local n_mod = r(N)
        quietly count if flag_D3_`v'_sev == 1
        di as txt "  `v': mod=" `n_mod' "  sev=" r(N)
    }
}

* ============================================================
* SECTION 4 — D2: LONGITUDINAL GROWTH-RATE OUTLIER
* ============================================================
* Requires consecutive firm-year pairs (xtset psid year).
* Structural gap years: flag suppressed when the lag year crosses
* a known survey gap (the change is not a genuine year-on-year shift).

di as txt _n "=== D2: Longitudinal growth-rate outlier ==="

* Re-sort after merges in D1/D3 which may disrupt panel order
sort psid year
xtset psid year

foreach v of local flag_vars {

    gen byte flag_D2_`v'_mod = .
    gen byte flag_D2_`v'_sev = .

    * Log-ratio: defined only when both t and t-1 are positive AND consecutive
    gen double _logv_t  = log(`v')   if `v'   > 0 & !missing(`v')
    gen double _logv_L1 = log(L.`v') if L.`v' > 0 & !missing(L.`v')

    * Consecutive years: lag year == current year - 1
    gen byte _consec = (L.year == year - 1) if !missing(L.year)

    gen double _logratio = _logv_t - _logv_L1 ///
        if !missing(_logv_t) & !missing(_logv_L1) & _consec == 1

    * Suppress flag if the lag crosses a structural gap year
    * (gap year means the variable was not collected in year t-1,
    *  so the first post-gap year is NOT a year-on-year comparison)
    local gaplist "`gap_`v''"
    if "`gaplist'" != "" {
        foreach gy of local gaplist {
            local gy_next = `gy' + 1
            * The ratio computed in the first post-gap year is invalid
            replace _logratio = . if year == `gy_next' & _consec == 1
        }
    }

    replace flag_D2_`v'_mod = (abs(_logratio) > `ln_mod') if !missing(_logratio)
    replace flag_D2_`v'_sev = (abs(_logratio) > `ln_sev') if !missing(_logratio)

    label variable flag_D2_`v'_mod "D2 mod: |Δlog(`v')| > log(10) — 10× year-on-year change"
    label variable flag_D2_`v'_sev "D2 sev: |Δlog(`v')| > log(50) — 50× year-on-year change"

    drop _logv_t _logv_L1 _consec _logratio

    quietly count if flag_D2_`v'_mod == 1
    local n_mod = r(N)
    quietly count if flag_D2_`v'_sev == 1
    di as txt "  `v': mod=" `n_mod' "  sev=" r(N)
}

* ============================================================
* SECTION 6 — COMPOSITE FLAGS
* ============================================================
di as txt _n "=== Composite flags ==="

gen int  flag_n_dims  = 0     // count of dimensions triggered (0–3)
gen byte flag_any_mod = 0     // any moderate or stronger flag
gen byte flag_any_sev = 0     // any severe flag

foreach v of local flag_vars {
    * D1
    foreach tier in mod sev {
        cap replace flag_any_mod  = max(flag_any_mod, flag_D1_`v'_`tier') ///
            if !missing(flag_D1_`v'_`tier')
        if "`tier'" == "sev" {
            cap replace flag_any_sev = max(flag_any_sev, flag_D1_`v'_sev) ///
                if !missing(flag_D1_`v'_sev)
        }
    }
    * D2
    foreach tier in mod sev {
        cap replace flag_any_mod = max(flag_any_mod, flag_D2_`v'_`tier') ///
            if !missing(flag_D2_`v'_`tier')
        if "`tier'" == "sev" {
            cap replace flag_any_sev = max(flag_any_sev, flag_D2_`v'_sev) ///
                if !missing(flag_D2_`v'_sev)
        }
    }
    * D3
    foreach tier in mod sev {
        cap replace flag_any_mod = max(flag_any_mod, flag_D3_`v'_`tier') ///
            if !missing(flag_D3_`v'_`tier')
        if "`tier'" == "sev" {
            cap replace flag_any_sev = max(flag_any_sev, flag_D3_`v'_sev) ///
                if !missing(flag_D3_`v'_sev)
        }
    }
}

* Count of dimensions (use severe flags for conciseness)
foreach v of local flag_vars {
    cap replace flag_n_dims = flag_n_dims + (flag_D1_`v'_sev == 1)
    cap replace flag_n_dims = flag_n_dims + (flag_D2_`v'_sev == 1)
    cap replace flag_n_dims = flag_n_dims + (flag_D3_`v'_sev == 1)
}

label variable flag_any_mod  "Any moderate+ flag triggered (D1–D3)"
label variable flag_any_sev  "Any severe flag triggered (D1–D3)"
label variable flag_n_dims   "Count of (variable × dimension) pairs with severe flag triggered (0–33: 3 dims × 11 vars)"

di as txt _n "  Summary:"
quietly count if flag_any_mod  == 1
di as txt "  flag_any_mod:  " r(N) " obs (" %5.2f `=100*r(N)/_N' "%)"
quietly count if flag_any_sev  == 1
di as txt "  flag_any_sev:  " r(N) " obs (" %5.2f `=100*r(N)/_N' "%)"

tab flag_n_dims

* ============================================================
* SECTION 7 — SUMMARY TABLES
* ============================================================
di as txt _n "=== Summary tables ==="

* Collect all flag variables
quietly ds flag_D1_* flag_D2_* flag_D3_* flag_any_mod flag_any_sev flag_n_dims
local flag_sumvars `r(varlist)'

* By year
preserve
    collapse (sum) `flag_sumvars' (count) n_obs = psid, by(year)
    export delimited using "$tables/flag_summary_by_year.csv", replace
    di as txt "  Saved: $tables/flag_summary_by_year.csv"
restore

* By ISIC2
preserve
    keep if !missing(isic2)
    collapse (sum) `flag_sumvars' (count) n_obs = psid, by(isic2)
    export delimited using "$tables/flag_summary_by_isic2.csv", replace
    di as txt "  Saved: $tables/flag_summary_by_isic2.csv"
restore

* ============================================================
* SECTION 8 — SAVE
* ============================================================
save "$output/si_energy_flagged.dta", replace
di as txt _n "Saved: $output/si_energy_flagged.dta"
di as txt "  Obs: " _N
quietly ds flag_*
di as txt "  Flag variables: `: word count `r(varlist)''"

di as txt _n "=== Robustness sample sizes ==="
quietly count
di as txt "  Full sample:                     " r(N)
quietly count if flag_any_mod == 0
di as txt "  Drop any moderate flag:          " r(N)
quietly count if flag_any_sev == 0
di as txt "  Drop any severe flag:            " r(N)
quietly count if flag_n_dims == 0
di as txt "  Drop any dimension (severe):     " r(N)
quietly count if flag_n_dims < 2
di as txt "  Keep < 2 severe dimensions:      " r(N)

log close
